language: elixir
matrix:
  include:
    - otp_release: "24.1"
      elixir: "1.12.3"
sudo: false
before_script:
  - mix deps.get --only test
script:
  - MIX_ENV=test mix test
  - MIX_ENV=test mix coveralls.travis
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
